global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Collections;
global using AngleSharp.Dom;
global using AngleSharp.Diffing.Core;
global using AngleSharp.Diffing.Extensions;
global using AngleSharp.Html.Parser;
global using AngleSharp.Css.Dom;
global using System.Runtime.Serialization;